### PR TITLE
add nginx 1.15.7 patch

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
retest this please Jenkins

**Comment by kaleb-himes** [comment]
retest this please jenkins

**Comment by JacobBarthelmeh** [comment]
Initially tested when this was opened using nginx-tests, it's really close to the 1.15.0 patch. The most recent test was a build time test with Yocto that caught the options.h include was missing.

**Review by julek-wolfssl — APPROVED** [review]

**Comment by julek-wolfssl** [comment]
Builds and can pass most tests.

**Pull request merged**
